import { LocaleContent } from './types';

export const enContent: LocaleContent = {
  nav: {
    brandName: 'CRE Calculators',
    calculators: 'All Calculators',
    capRate: 'Cap Rate',
    noi: 'NOI',
    cashOnCash: 'Cash-on-Cash',
    loanPayment: 'Loan Payment',
    dscr: 'DSCR',
    exchange1031: '1031 Exchange',
    leaseVsBuy: 'Lease vs Buy',
    breakEvenRatio: 'Break-Even Ratio',
    guides: 'Guides & Benchmarks',
    about: 'About',
    switchLangLabel: '中文',
    switchLangTarget: 'zh',
    switchLangCode: 'zh',
  },
  home: {
    metaTitle: 'Commercial Real Estate Investment Calculators | CRE Tools',
    metaDescription: 'Free, professional commercial real estate investment calculators for cap rate, NOI, cash-on-cash return, loan payment, DSCR, and deal analysis. Made for investors and brokers.',
    heroH1: 'Commercial Real Estate Investment Decision Tools',
    heroSubtitle: 'Instant, precise financial calculators backed by clear formulas, real-world examples, and industry benchmarks.',
    featuredTitle: 'Essential CRE Calculators',
    featuredDesc: 'Evaluate property yield, cash flow, and debt coverage with our instant client-side tools.',
    calculators: [
      {
        slug: 'cap-rate',
        title: 'Cap Rate Calculator',
        description: 'Find the capitalization rate for any property or work backward to calculate your max purchase price.',
        badge: 'High Priority',
      },
      {
        slug: 'noi',
        title: 'NOI (Net Operating Income) Calculator',
        description: 'Calculate net operating income after vacancy and operating expenses—the foundation of all CRE metrics.',
        badge: 'Essential',
      },
      {
        slug: 'cash-on-cash',
        title: 'Cash-on-Cash Return Calculator',
        description: 'Measure your real annual return on cash invested after loan payments and upfront closing costs.',
        badge: 'Leverage',
      },
      {
        slug: 'loan-payment',
        title: 'Commercial Loan Payment Calculator',
        description: 'Calculate monthly principal & interest payments, total interest, balloon payoff balances, and amortization schedules.',
        badge: 'Financing',
      },
      {
        slug: 'dscr',
        title: 'DSCR (Debt Service Coverage Ratio) Calculator',
        description: 'Evaluate property cash flow safety margin against annual debt service to meet lender underwriting criteria.',
        badge: 'Underwriting',
      },
      {
        slug: '1031-exchange',
        title: '1031 Exchange Tax Deferral Calculator',
        description: 'Estimate deferred capital gains tax and replacement property purchasing rules for 1031 like-kind exchanges.',
        badge: 'Tax Planning',
      },
      {
        slug: 'lease-vs-buy',
        title: 'Lease vs Buy Calculator',
        description: 'Compare full lifecycle cost and net equity accumulation between leasing and buying commercial space.',
        badge: 'Occupier Strategy',
      },
      {
        slug: 'break-even-ratio',
        title: 'Break-Even Ratio Calculator',
        description: 'Determine the minimum occupancy rate required to cover operating expenses and mortgage debt service.',
        badge: 'Risk Analysis',
      },
    ],
    whyUsTitle: 'Built for Serious CRE Investors & Brokers',
    whyUsItems: [
      {
        title: 'Instant & Client-Side',
        desc: 'All calculations run in real time right in your browser. No registration or server delays.',
      },
      {
        title: 'Transparent Formulas & Examples',
        desc: 'Every tool includes step-by-step formula breakdowns and real scenarios so you understand the numbers.',
      },
      {
        title: 'Dual US & Global Perspective',
        desc: 'Tailored for US commercial property standards, underwriting practices, and investor requirements.',
      },
    ],
  },
  capRate: {
    metaTitle: 'Cap Rate Calculator — Commercial Real Estate Cap Rate Tool',
    metaDescription: 'Calculate capitalization rate for any commercial property in seconds. Enter purchase price and NOI to find your cap rate, or work backward from a target cap rate to find max purchase price.',
    h1: 'Cap Rate Calculator',
    subtitle: 'Find the capitalization rate for any commercial property — or work backward to find your maximum purchase price.',
    whatIsTitle: 'What Is Cap Rate and Why It Matters',
    whatIsContent: "Cap rate (capitalization rate) is the most common shorthand investors use to compare commercial properties at a glance. It tells you the annual return a property would generate if you bought it in all cash, based purely on its net operating income relative to the purchase price. It's not a complete picture of your actual return — it ignores financing, taxes, and future appreciation — but it's the fastest way to compare two properties or sanity-check a listing price against the market.",
    formulaTitle: 'The Formula',
    formulaCode: 'Cap Rate = Net Operating Income (NOI) / Purchase Price × 100%',
    formulaVariables: [
      { label: 'NOI', desc: 'Annual income after operating expenses, before debt service and taxes' },
      { label: 'Purchase Price', desc: "The property's acquisition price (or current market value, if you're evaluating a property you already own)" },
    ],
    exampleTitle: 'A Real Example',
    exampleContent: 'Say you\'re looking at a small retail strip center listed at $2,400,000, with an NOI of $168,000/year.\n\nCap Rate = $168,000 / $2,400,000 = 7.0%\n\nIf you know your target cap rate is 7.5% and the NOI is fixed at $168,000, you can work backward: Max Purchase Price = $168,000 / 0.075 = $2,240,000 — meaning the listing is priced above what a 7.5% target would justify.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: "What's a good cap rate for commercial real estate?",
        answer: 'It depends heavily on asset class and location. Multifamily in a strong metro might trade at 4-5%, while a single-tenant net-lease property in a secondary market might trade at 7-9%. Lower cap rates generally signal lower perceived risk (and lower yield); higher cap rates signal higher risk or yield.',
      },
      {
        question: "What's the difference between cap rate and cash-on-cash return?",
        answer: 'Cap rate assumes an all-cash purchase and ignores your financing. Cash-on-cash return accounts for your actual cash invested (after a loan), so it reflects your real leveraged return.',
      },
      {
        question: 'Does cap rate account for financing?',
        answer: "No. Cap rate is calculated independent of how the deal is financed, which is exactly why it's useful for comparing properties apples-to-apples — regardless of each buyer's loan terms.",
      },
      {
        question: 'Can I use cap rate to value a property I already own?',
        answer: "Yes — plug in your property's current NOI and an estimated market value (or ask a broker for comparable sales) to see roughly where your cap rate sits relative to the market.",
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'NOI Calculator', slug: 'noi' },
      { title: 'Cash-on-Cash Return Calculator', slug: 'cash-on-cash' },
      { title: '1031 Exchange Calculator', slug: '1031-exchange' },
      { title: 'Break-Even Ratio Calculator', slug: 'break-even-ratio' },
    ],
  },
  noi: {
    metaTitle: 'NOI Calculator — Net Operating Income for Commercial Property',
    metaDescription: 'Calculate net operating income (NOI) for any commercial property. Enter gross income, vacancy loss, and operating expenses to get your annual and monthly NOI.',
    h1: 'NOI Calculator (Net Operating Income)',
    subtitle: "Find your property's net operating income — the number every other CRE metric is built on.",
    whatIsTitle: 'What Is NOI and Why It Matters',
    whatIsContent: 'NOI is the foundation metric in commercial real estate. Almost every other calculation — cap rate, cash-on-cash return, loan payment — starts with NOI. It represents how much income a property actually generates from operations, before you factor in your mortgage payment or income taxes. Lenders, appraisers, and buyers all look at NOI first because it isolates the property\'s performance from how any particular owner chose to finance it.',
    formulaTitle: 'The Formula',
    formulaCode: 'NOI = Effective Gross Income (EGI) − Operating Expenses\nEGI = Gross Income − Vacancy & Credit Loss',
    formulaVariables: [
      { label: 'Effective Gross Income (EGI)', desc: 'Gross potential rental income minus expected vacancy and unpaid rent' },
      { label: 'Operating Expenses', desc: 'Property taxes, insurance, repairs/maintenance, management fees, landlord utilities. Excludes debt service, capital improvements, and income taxes.' },
    ],
    exampleTitle: 'A Real Example',
    exampleContent: 'A 12-unit apartment building generates $312,000/year in gross rental income. You estimate 5% vacancy loss ($15,600), and operating expenses run $94,000/year (taxes, insurance, maintenance, management fee).\n\nEGI = $312,000 − $15,600 = $296,400\nNOI = $296,400 − $94,000 = $202,400/year (about $16,867/month)',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'Does NOI include mortgage payments?',
        answer: 'No. NOI is calculated before debt service. Your loan payment is subtracted later, when you calculate cash flow — not NOI.',
      },
      {
        question: 'What counts as an operating expense?',
        answer: 'Property taxes, insurance, repairs and maintenance, property management fees, utilities the landlord pays, and reserves for replacement. Capital improvements (like a new roof) and mortgage payments are excluded.',
      },
      {
        question: 'Why do lenders care so much about NOI?',
        answer: 'Lenders use NOI to calculate debt service coverage ratio (DSCR) — essentially, whether the property generates enough income to comfortably cover the loan payment. Low or shrinking NOI is a red flag in underwriting.',
      },
      {
        question: 'How is NOI different from cash flow?',
        answer: 'NOI is before debt service; cash flow is after. Cash flow = NOI − annual debt service (and sometimes − capital reserves).',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
      { title: 'DSCR Calculator', slug: 'dscr' },
      { title: 'Break-Even Ratio Calculator', slug: 'break-even-ratio' },
      { title: '1031 Exchange Calculator', slug: '1031-exchange' },
    ],
  },
  cashOnCash: {
    metaTitle: 'Cash-on-Cash Return Calculator — Real Estate Investment Tool',
    metaDescription: 'Calculate your cash-on-cash return on a leveraged commercial real estate deal. Enter annual cash flow and total cash invested to find your real return on invested capital.',
    h1: 'Cash-on-Cash Return Calculator',
    subtitle: 'Find your real return on the actual cash you put into a deal — after financing.',
    whatIsTitle: 'What Is Cash-on-Cash Return and Why It Matters',
    whatIsContent: 'Cash-on-cash return measures the annual pre-tax cash flow you actually receive, relative to the actual cash you put into the deal — your down payment, closing costs, and any upfront capital improvements. Unlike cap rate, it accounts for leverage, which means it\'s the number that tells you how hard your invested dollars are working, not how the property performs in the abstract.',
    formulaTitle: 'The Formula',
    formulaCode: 'Cash-on-Cash Return = Annual Pre-Tax Cash Flow / Total Cash Invested × 100%',
    formulaVariables: [
      { label: 'Annual Cash Flow', desc: 'NOI minus annual debt service (loan payments)' },
      { label: 'Total Cash Invested', desc: 'Down payment + closing costs + any immediate capital expenditures — not the full purchase price' },
    ],
    exampleTitle: 'A Real Example',
    exampleContent: 'You buy a $1,200,000 property with a 25% down payment ($300,000) plus $30,000 in closing costs and immediate repairs — total cash invested is $330,000. Annual NOI is $84,000, and your annual loan payment (debt service) is $54,000.\n\nAnnual Cash Flow = $84,000 − $54,000 = $30,000\nCash-on-Cash Return = $30,000 / $330,000 = 9.1%\n\nCompare that to the property\'s cap rate ($84,000 / $1,200,000 = 7.0%) — the leverage here is boosting your cash return above the unleveraged cap rate, because the cost of debt is lower than the property\'s yield.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'Why is cash-on-cash return usually different from cap rate?',
        answer: 'Cap rate assumes no financing. Cash-on-cash return reflects leverage. If your loan\'s interest rate is lower than the property\'s cap rate, leverage typically boosts your cash-on-cash return above the cap rate (positive leverage). If the interest rate is higher, it works against you (negative leverage).',
      },
      {
        question: 'What counts as "cash invested"?',
        answer: 'Down payment, closing costs, loan origination fees, and any immediate repairs or upgrades needed before the property is rent-ready. It does not include the financed portion of the purchase price.',
      },
      {
        question: 'Is a higher cash-on-cash return always better?',
        answer: 'Not necessarily — a very high cash-on-cash return can also signal high leverage and higher risk (a bigger loan relative to a smaller down payment). Look at it alongside your mortgage payment to understand your risk cushion.',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
      { title: 'Break-Even Ratio Calculator', slug: 'break-even-ratio' },
      { title: '1031 Exchange Calculator', slug: '1031-exchange' },
      { title: 'DSCR Calculator', slug: 'dscr' },
    ],
  },
  loanPayment: {
    metaTitle: 'Commercial Loan Payment Calculator — Equal Installment vs Equal Principal & Balloon Payoff',
    metaDescription: 'Compare Equal Installment (fixed monthly payment) and Equal Principal (declining payment) repayment methods for commercial loans. Calculate monthly payments, interest costs, balloon payoff, and amortization.',
    h1: 'Commercial Real Estate Loan Payment Calculator',
    subtitle: 'Switch between Equal Installment and Equal Principal repayment methods to calculate monthly debt service, interest costs, and balloon payoff amounts.',
    whatIsTitle: 'Commercial Loan Repayment Methods & Balloon Payoffs',
    whatIsContent: 'Commercial mortgages feature shorter loan maturity terms (such as 5, 7, or 10 years) paired with longer amortization periods (such as 25 or 30 years). At maturity, the remaining principal balance must be paid off or refinanced via a balloon payment.\n\nTwo primary repayment methods are available for commercial debt:\n1. Equal Installment (Fixed Payment): Monthly principal & interest payment remains constant throughout the term. Interest dominates early payments, so the remaining balloon balance at maturity is higher.\n2. Equal Principal (Declining Payment): A fixed portion of principal (P/n) is paid each month, while interest decreases as principal declines. Early payments are higher, but principal balance drops faster, resulting in a substantially lower balloon payment at loan maturity.',
    formulaTitle: 'The Formulas',
    formulaCode: '【Equal Installment (Fixed Monthly Payment)】\nM = P × [ r(1 + r)^n ] / [ (1 + r)^n − 1 ]\n\n【Equal Principal (Declining Monthly Payment)】\nPayment at Month m (M_m) = (P / n) + [ P − (m − 1) × (P / n) ] × r\nFixed Monthly Principal = P / n',
    formulaVariables: [
      { label: 'P', desc: 'Principal Loan Amount ($)' },
      { label: 'r', desc: 'Monthly Interest Rate (Annual Rate / 12)' },
      { label: 'n', desc: 'Total Amortization Payments (Amortization Years × 12)' },
      { label: 'm', desc: 'Payment Month Number (1 through n)' },
    ],
    exampleTitle: 'Real Scenario Comparison ($1.3M Loan, 6.5% Rate, 25-Yr Amort, 10-Yr Maturity)',
    exampleContent: '',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'What is the main difference between Equal Installment and Equal Principal repayment?',
        answer: 'Equal Installment provides a fixed monthly payment for predictable budgeting, but principal pays down slower. Equal Principal pays down a fixed amount of principal each month; while early payments are higher, total interest is lower and the balloon payoff at maturity is significantly smaller.',
      },
      {
        question: 'What is a balloon payment in commercial real estate?',
        answer: 'A balloon payment is a lump-sum principal balance due at loan maturity (e.g., Year 10) when the loan term is shorter than the amortization schedule (e.g., 25 years). Investors typically refinance or sell before maturity.',
      },
      {
        question: 'What are standard amortization and maturity terms for commercial mortgages?',
        answer: 'Most commercial mortgages use a 25-year amortization schedule to set monthly payments, paired with a 5, 7, or 10-year loan maturity term. Prime institutional assets may qualify for 30-year amortization.',
      },
      {
        question: 'How should investors choose between the two repayment methods?',
        answer: 'Choose Equal Installment if early cash flow is tight and you prefer predictable debt service. Choose Equal Principal if NOI is strong and you want to minimize interest expenses and reduce refinancing risk at loan maturity.',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'Lease vs Buy Calculator', slug: 'lease-vs-buy' },
      { title: 'DSCR Calculator', slug: 'dscr' },
      { title: 'NOI Calculator', slug: 'noi' },
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
    ],
  },
  dscr: {
    metaTitle: 'DSCR Calculator — Debt Service Coverage Ratio for Commercial Loans',
    metaDescription: 'Calculate the Debt Service Coverage Ratio (DSCR) for commercial real estate mortgages. Evaluate property cash flow against annual debt service to meet lender underwriting standards.',
    h1: 'DSCR (Debt Service Coverage Ratio) Calculator',
    subtitle: "Evaluate whether your property's net operating income (NOI) comfortably covers your annual mortgage debt service.",
    whatIsTitle: 'What Is DSCR and Why It Matters',
    whatIsContent: 'The Debt Service Coverage Ratio (DSCR) is the single most important risk metric used by commercial real estate lenders to evaluate mortgage applications. It measures a property\'s annual Net Operating Income (NOI) against its annual debt service (total principal and interest payments), reflecting the safety margin between operational cash flow and mortgage obligations.\n\nCommercial banks and institutional lenders typically require a minimum DSCR of 1.20x to 1.25x. This buffer ensures that the property generates sufficient surplus cash flow to withstand unexpected vacancy spikes, rent concessions, or rising operating expenses without defaulting on loan payments.',
    formulaTitle: 'The Formula',
    formulaCode: 'DSCR = Annual NOI / Annual Debt Service',
    formulaVariables: [
      { label: 'Annual Net Operating Income (NOI)', desc: 'Effective gross rental income minus operating expenses (before debt service and income taxes)' },
      { label: 'Annual Debt Service', desc: 'Total principal and interest paid over 12 months' },
    ],
    exampleTitle: 'A Real Commercial Real Estate Example ($2M Office Building)',
    exampleContent: 'Suppose you are purchasing a commercial office building for $2,000,000 with a $1,500,000 mortgage. The property generates $220,000 in effective gross income and incurs $70,000 in operating expenses, resulting in an annual NOI of $150,000.\n\nAt a 6.5% interest rate on a 25-year amortization schedule, monthly debt service is $10,128, bringing annual debt service to $121,536.\n\nDSCR = $150,000 / $121,536 = 1.23x\n\n【Interpretation】: A 1.23x ratio is near the standard lender threshold (1.20 - 1.25x). A lender might require a slightly larger down payment or debt service reserve fund to approve the loan.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'What is a good DSCR ratio for a commercial real estate loan?',
        answer: 'Most commercial banks, CMBS lenders, and life insurance companies require a minimum DSCR between 1.20x and 1.25x. Stabilized single-tenant net-lease properties may qualify at 1.15x, while higher-risk asset classes (like hospitality or value-add retail) often require 1.35x to 1.50x.',
      },
      {
        question: 'What happens if DSCR falls below 1.0?',
        answer: 'A DSCR below 1.0x means the property does not generate enough net operating income to cover its debt payments (negative cash flow). Lenders will decline new loan applications, and for existing loans, a sub-1.0 DSCR can trigger default covenants requiring the borrower to pay down principal.',
      },
      {
        question: "How can an investor improve a property's DSCR?",
        answer: 'You can increase DSCR by either increasing NOI (raising rents, reducing vacancy, cutting operating costs) or lowering annual debt service (increasing your down payment to borrow less, negotiating a lower interest rate, or extending the amortization period).',
      },
      {
        question: 'How does DSCR differ from Cap Rate and Cash-on-Cash Return?',
        answer: 'Cap Rate measures property return independent of debt; Cash-on-Cash Return measures leveraged equity return; DSCR measures debt coverage safety margin. Lenders rely on DSCR to dictate maximum loan sizing.',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'NOI Calculator', slug: 'noi' },
      { title: 'Commercial Loan Payment Calculator', slug: 'loan-payment' },
      { title: '1031 Exchange Calculator', slug: '1031-exchange' },
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
    ],
  },
  exchange1031: {
    metaTitle: '1031 Exchange Calculator — Tax Deferred Real Estate Investment Tool',
    metaDescription: 'Calculate deferred capital gains taxes for 1031 like-kind exchanges. Enter sale price, original cost basis, selling expenses, and tax rate to evaluate tax savings and replacement property rules.',
    h1: '1031 Exchange Tax Deferral Calculator',
    subtitle: 'Estimate deferred capital gains tax and replacement property purchasing rules when exchanging commercial real estate.',
    whatIsTitle: 'What Is a 1031 Exchange and Why It Matters',
    whatIsContent: 'Under Section 1031 of the Internal Revenue Code (IRC Section 1031), commercial and investment real estate owners can defer paying capital gains tax and depreciation recapture tax upon selling a property, provided the proceeds are reinvested into a "like-kind" replacement property of equal or greater value.\n\nA 1031 Exchange is one of the most powerful wealth-building mechanisms in commercial real estate, enabling investors to keep 100% of their equity working for them rather than forfeiting a substantial portion to taxes. To achieve full tax deferral, two primary rules apply:\n1. The replacement property purchase price must be equal to or greater than the net sales price of the relinquished property (Sale Price minus Selling Costs).\n2. All net cash equity from the sale must be reinvested into the replacement property.',
    formulaTitle: 'The Formulas',
    formulaCode: 'Realized Capital Gain = Sale Price − Selling Expenses − Original Cost Basis\nEstimated Tax Deferred = Realized Gain × Combined Tax Rate',
    formulaVariables: [
      { label: 'Sale Price', desc: 'Contract gross sales price of the relinquished property' },
      { label: 'Selling Expenses', desc: 'Broker commissions, title fees, legal fees, and escrow costs' },
      { label: 'Original Cost Basis', desc: 'Original purchase price plus capital improvements (before depreciation deduction)' },
      { label: 'Combined Tax Rate', desc: 'Estimated combined rate including Federal Capital Gains (15-20%), State Tax, Depreciation Recapture (25%), and NIIT (3.8%)' },
    ],
    exampleTitle: 'A Real 1031 Exchange Example ($2.5M Sale)',
    exampleContent: 'Suppose you purchased a commercial building 8 years ago for $1,200,000 and are now selling it for $2,500,000 with $150,000 in closing costs. Your estimated combined tax rate is 25%.\n\nNet Sale Proceeds = $2,500,000 − $150,000 = $2,350,000\nRealized Capital Gain = $2,350,000 − $1,200,000 = $1,150,000\nTax Liability Without 1031 = $1,150,000 × 25% = $287,500\n\n【1031 Exchange Result】: By completing a 1031 Exchange through a Qualified Intermediary (QI), you defer the entire $287,500 tax bill. You must identify replacement properties within 45 days and close on a replacement property priced at $2,350,000 or more within 180 days, preserving your full $287,500 in equity.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'How do the 45-day and 180-day deadlines work in a 1031 exchange?',
        answer: 'Both deadlines start on the day the relinquished property closes. You have exactly 45 calendar days to formally identify up to 3 candidate replacement properties in writing to your QI, and 180 calendar days (or until your tax filing date) to close on the acquisition. These deadlines are strictly enforced with no extensions.',
      },
      {
        question: 'What is a Qualified Intermediary (QI)?',
        answer: 'IRS regulations strictly prohibit sellers from taking constructive receipt of sale proceeds. A Qualified Intermediary (QI) is a neutral third-party entity that holds sale funds in an escrow account and transfers them directly to the closing agent for the replacement property.',
      },
      {
        question: 'What happens if I purchase a replacement property of lower value?',
        answer: 'If the replacement property costs less than your net sales price, or if you retain any cash equity, the difference is classified as "boot." Boot is taxable up to the amount of your realized gain.',
      },
      {
        question: 'Can I use a 1031 exchange for a primary residence?',
        answer: 'No. IRC Section 1031 applies exclusively to property held for investment or productive use in a trade or business. Primary personal residences do not qualify (primary home capital gain exclusions fall under IRC Section 121).',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
      { title: 'NOI Calculator', slug: 'noi' },
      { title: 'Cash-on-Cash Return Calculator', slug: 'cash-on-cash' },
    ],
  },
  leaseVsBuy: {
    metaTitle: 'Lease vs Buy Calculator — Commercial Real Estate Analysis Tool',
    metaDescription: 'Compare the full lifecycle cost of leasing versus buying commercial property over a 5 to 15 year holding period, accounting for rent escalations, mortgage paydown, and equity appreciation.',
    h1: 'Lease vs Buy Calculator',
    subtitle: 'Evaluate full lifecycle costs, cash outlays, and asset appreciation between leasing and buying commercial property.',
    whatIsTitle: 'What Is a Lease vs Buy Analysis and Why It Matters',
    whatIsContent: 'A Lease vs Buy analysis is the fundamental financial framework used by owner-occupiers and business owners when deciding whether to lease or purchase office, retail, or industrial space.\n\nLeasing requires lower upfront capital and offers operational flexibility, but 100% of lease payments represent unrecoverable expenses with zero equity build-up. Purchasing requires an initial down payment and ongoing mortgage debt service, but monthly principal paydown acts as a forced savings mechanism while building substantial long-term equity through property appreciation.',
    formulaTitle: 'The Formulas',
    formulaCode: 'Total Lease Outlay = Sum of [ Annual Rent × (1 + Escalation Rate)^Year ]\nNet Buy Outlay = Down Payment + Cumulative Mortgage Paid − Net Sale Proceeds at Exit\nNet Sale Proceeds = Purchase Price × (1 + Appreciation Rate)^Years × (1 − Selling Cost %) − Remaining Balance',
    formulaVariables: [
      { label: 'Rent & Escalation', desc: 'Initial monthly rent and annual contractual rent escalation rate (typically 2.5% - 3.5%)' },
      { label: 'Purchase & Down Payment', desc: 'Property purchase price and equity down payment (SBA 504 loans require as low as 10% down; conventional 25%)' },
      { label: 'Appreciation & Exit Cost', desc: 'Expected annual property growth rate and broker commissions/closing costs upon sale (typically 5% - 6%)' },
    ],
    exampleTitle: 'A Real 10-Year Lease vs Buy Example ($1.8M Purchase vs $10k/mo Rent)',
    exampleContent: 'Suppose a company requires an office space for 10 years:\n- Option A (Lease): Initial monthly rent of $10,000 with 3.0% annual escalation. Total rent paid over 10 years = $1,375,666.\n- Option B (Buy): Purchase price of $1,800,000 with 25% down ($450,000) and $1,350,000 loan (6.5% interest, 25-yr amort). Annual appreciation of 3.0% and 5% selling cost at Year 10.\n  - Total mortgage debt service paid over 10 years = $1,093,836\n  - Property value grows to $2,419,049 at Year 10. Net sale proceeds after selling costs and remaining loan balance ($1,046,403) = $1,251,694\n  - Net Cost of Buying = $450,000 + $1,093,836 − $1,251,694 = $292,142\n\n【Result】: Buying saves approximately $1,083,524 over the 10-year holding period compared to leasing.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'When should a company choose to lease instead of buy?',
        answer: 'Companies in rapid growth phases, those needing to preserve capital for core operations, or businesses with uncertain spatial requirements (likely to move in 3-5 years) should choose leasing to maintain capital agility.',
      },
      {
        question: 'What loan options exist for owner-occupier buyers?',
        answer: 'In the US, owner-occupiers (occupying >51% of space) can leverage SBA 504 or SBA 7(a) loan programs, which offer down payments as low as 10% with long-term 25-year fixed financing terms.',
      },
      {
        question: 'How is the "Net Outlay" calculated for the buying option?',
        answer: 'Net Outlay accounts for equity recovery upon sale: Net Outlay = (Down Payment + Total Mortgage Debt Service Paid) minus (Net Cash Realized from Selling at Exit). Because accumulated equity and appreciation are recovered at sale, net purchasing cost is often far lower than total rent over long horizons.',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'Commercial Loan Payment Calculator', slug: 'loan-payment' },
      { title: 'DSCR Calculator', slug: 'dscr' },
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
    ],
  },
  breakEvenRatio: {
    metaTitle: 'Break-Even Ratio Calculator — Commercial Real Estate Risk Metric',
    metaDescription: 'Calculate Break-Even Ratio (BER) for commercial real estate properties. Enter operating expenses, annual debt service, and Effective Gross Income to assess occupancy safety margins.',
    h1: 'Break-Even Ratio Calculator',
    subtitle: 'Determine the minimum occupancy rate required to cover operating expenses and mortgage debt service.',
    whatIsTitle: 'What Is the Break-Even Ratio and Why It Matters',
    whatIsContent: 'The Break-Even Ratio (BER) is a fundamental risk evaluation metric used by commercial real estate lenders and underwriting teams to gauge a property\'s vulnerability to vacancy and negative cash flow.\n\nBER shows the exact percentage of occupancy (or gross revenue) required to pay all operating expenses and annual mortgage debt service combined. A lower BER indicates a larger safety margin, meaning the property can weather economic downturns, tenant defaults, or rising expenses. Commercial lenders typically require a BER below 80% to 85%.',
    formulaTitle: 'The Formulas',
    formulaCode: 'Break-Even Ratio (%) = ( Operating Expenses + Annual Debt Service ) / Effective Gross Income (EGI) × 100%\nMax Allowable Vacancy (%) = 100% − Break-Even Ratio',
    formulaVariables: [
      { label: 'Operating Expenses', desc: 'Total annual costs to operate the property (property taxes, insurance, management, repairs, utilities)' },
      { label: 'Annual Debt Service', desc: 'Total annual mortgage principal and interest payments (12 × Monthly Payment)' },
      { label: 'Effective Gross Income (EGI)', desc: 'Gross potential rent minus estimated vacancy and credit losses plus secondary income' },
    ],
    exampleTitle: 'A Real Office Property Break-Even Example ($220k EGI)',
    exampleContent: 'Suppose you own a commercial office building generating $220,000 in Effective Gross Income (EGI), with $70,000 in annual operating expenses and $121,536 in annual debt service:\n\nTotal Fixed Outlay = $70,000 + $121,536 = $191,536\nBreak-Even Ratio (BER) = ($191,536 / $220,000) × 100% = 87.06%\nMax Allowable Vacancy = 100% − 87.06% = 12.94%\n\n【Interpretation】: Because BER is 87.06% (exceeding lender target benchmarks of 80-85%), the financial cushion against vacancy is thin. If vacancy exceeds 12.94%, the property will experience a cash flow deficit.',
    faqTitle: 'Frequently Asked Questions',
    faqs: [
      {
        question: 'What is a good Break-Even Ratio for commercial lenders?',
        answer: 'Most commercial lenders prefer a Break-Even Ratio under 80%. A BER below 80% signifies a robust financial cushion, making loan approval easier and interest terms more favorable.',
      },
      {
        question: 'How does Break-Even Ratio differ from DSCR?',
        answer: 'While DSCR measures net operating income against debt service (NOI / Debt Service), BER measures total fixed obligations (Expenses + Debt Service) against gross income (EGI). BER explicitly reveals the minimum required occupancy percentage to break even.',
      },
      {
        question: 'How can an investor lower a property\'s Break-Even Ratio?',
        answer: 'Investors can lower BER by reducing debt service (larger down payment or lower interest rate), auditing and curbing operating expenses, or increasing gross revenues through rent adjustments or amenity fees.',
      },
    ],
    relatedTitle: 'Related Calculators',
    relatedCalculators: [
      { title: 'DSCR Calculator', slug: 'dscr' },
      { title: 'NOI Calculator', slug: 'noi' },
      { title: 'Cap Rate Calculator', slug: 'cap-rate' },
    ],
  },
};
