import { LocaleContent } from './types';

export const zhContent: LocaleContent = {
  nav: {
    brandName: '商业地产投资计算器',
    calculators: '计算器总览',
    capRate: '资本化率 (Cap Rate)',
    noi: '净营业收入 (NOI)',
    cashOnCash: '现金回报率 (Cash-on-Cash)',
    loanPayment: '贷款月供 (Loan Payment)',
    dscr: '偿债覆盖率 (DSCR)',
    exchange1031: '1031 Exchange (递延税)',
    leaseVsBuy: 'Lease vs Buy (租买对比)',
    breakEvenRatio: 'Break-Even Ratio (收支平衡比)',
    guides: '基准数据与指南',
    about: '关于本站',
    switchLangLabel: 'English',
    switchLangTarget: 'en',
    switchLangCode: 'en',
  },
  home: {
    metaTitle: '商业地产投资计算器 | 美国商业地产决策工具站',
    metaDescription: '专为在美华人投资者与经纪人打造的商业地产投资决策计算工具，支持 Cap Rate、NOI、Cash-on-Cash Return、贷款月供、DSCR 偿债覆盖率实时计算与公式解读。',
    heroH1: '商业地产投资决策数字工具',
    heroSubtitle: '提供实时、精准的商业地产财务计算器，辅以公式讲解、真实场景示例与行业基准数据，助您快速评估项目价值。',
    featuredTitle: '核心商业地产计算器',
    featuredDesc: '基于纯前端实时计算，无须注册，即刻评估收益率、净现金流与还款摊销。',
    calculators: [
      {
        slug: 'cap-rate',
        title: '资本化率 (Cap Rate) 计算器',
        description: '快速算出任意商业地产的资本化率，或者反向推算你能接受的最高购买价。',
        badge: '核心指标',
      },
      {
        slug: 'noi',
        title: '净营业收入 (NOI) 计算器',
        description: '扣除空置损失与运营支出，计算物业的净营业收入——几乎所有商业地产指标的计算基础。',
        badge: '基础必备',
      },
      {
        slug: 'cash-on-cash',
        title: '现金回报率 (Cash-on-Cash) 计算器',
        description: '算出你实际投入的现金——在加了贷款杠杆之后——真正的税前年化现金回报率。',
        badge: '杠杆分析',
      },
      {
        slug: 'loan-payment',
        title: '贷款月供 (Loan Payment) 计算器',
        description: '计算每月本息还款额、利息成本、气球尾款金额及还款摊销表。',
        badge: '融资还款',
      },
      {
        slug: 'dscr',
        title: '偿债覆盖率 (DSCR) 计算器',
        description: '评估物业净营业收入 (NOI) 覆盖贷款债务本息的能力与商业银行风控门槛。',
        badge: '风控审核',
      },
      {
        slug: '1031-exchange',
        title: '1031 Exchange 递延税计算器',
        description: '估算出售商业地产时通过同类置换 (Like-Kind Exchange) 可延迟缴纳的资本利得税及再投资门槛。',
        badge: '税务规划',
      },
      {
        slug: 'lease-vs-buy',
        title: 'Lease vs Buy (租买对比) 计算器',
        description: '对比商业地产租赁与购买方案在 5-15 年持有期内的总现金支出与退出净资产积累。',
        badge: '租买决策',
      },
      {
        slug: 'break-even-ratio',
        title: '收支平衡比率 (Break-Even Ratio) 计算器',
        description: '计算商业地产物业满足运营支出与还贷债务所需的最低出租率门槛与抗空置安全垫。',
        badge: '风控安全',
      },
    ],
    whyUsTitle: '专为商业地产投资者与经纪人设计',
    whyUsItems: [
      {
        title: '纯前端实时响应',
        desc: '输入参数即刻显示计算结果与图表分析，零延迟，保障隐私安全。',
      },
      {
        title: '透明公式与场景化解读',
        desc: '拒绝黑盒计算。提供完整公式推导、实际案例与常见问题解答。',
      },
      {
        title: '深耕美国商业地产市场',
        desc: '全面适配美国商业地产市场习惯（USD / sq ft），提供专业术语对照。',
      },
    ],
  },
  capRate: {
    metaTitle: 'Cap Rate 计算器 — 商业地产资本化率在线计算工具',
    metaDescription: '输入物业价格和净营业收入（NOI），几秒钟算出Cap Rate；也可以反过来输入目标Cap Rate，算出你能接受的最高购买价格。',
    h1: '资本化率 (Cap Rate) 计算器',
    subtitle: '快速算出任意商业地产的资本化率，或者反向推算你能接受的最高购买价。',
    whatIsTitle: 'Cap Rate 是什么，为什么重要',
    whatIsContent: 'Cap Rate（资本化率）是商业地产投资者最常用的快速对比指标。它反映的是：如果你全款买下这个物业，单纯基于净营业收入和购买价格，每年能有多少回报率。它不是你实际回报的全貌——不考虑贷款、税务、未来增值这些因素——但它是快速对比两个物业、或者判断一个挂牌价格是否合理最直接的方法。',
    formulaTitle: '计算公式',
    formulaCode: 'Cap Rate = 净营业收入(NOI) / 购买价格 × 100%',
    formulaVariables: [
      { label: 'NOI', desc: '扣除运营支出之后、但在还贷和缴税之前的年收入' },
      { label: '购买价格', desc: '物业的购买价（如果是评估自己已持有的物业，可以用当前市场估值代替）' },
    ],
    exampleTitle: '一个真实场景示例',
    exampleContent: '假设你在看一处小型零售商铺，挂牌价240万美元，年NOI是16.8万美元。\n\nCap Rate = $168,000 / $2,400,000 = 7.0%\n\n如果你的目标Cap Rate是7.5%，NOI固定是16.8万美元，可以反向推算：最高可接受购买价 = $168,000 / 0.075 = $224万——也就是说，这个挂牌价其实比按7.5%目标应有的价格更贵。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '商业地产的Cap Rate多少算合理？',
        answer: '这个高度取决于资产类型和地段。核心城市的多户住宅（Multifamily）可能在4-5%左右交易，而次级市场的单租户净租赁物业（Net-Lease）可能在7-9%左右。Cap Rate越低，通常意味着市场认为风险越低（收益也越低）；Cap Rate越高，通常意味着风险或收益更高。',
      },
      {
        question: 'Cap Rate 和 Cash-on-Cash Return 有什么区别？',
        answer: 'Cap Rate假设你是全款购买，不考虑贷款；Cash-on-Cash Return则是基于你贷款后实际投入的现金计算，反映的是加了杠杆之后的真实回报率。可以参考我们的现金回报率 (Cash-on-Cash) 计算器。',
      },
      {
        question: 'Cap Rate 会把贷款因素算进去吗？',
        answer: '不会。Cap Rate的计算和融资方式完全无关，这正是它的优势——不管每个买家的贷款条件如何，都能做到"同一把尺子"横向对比。',
      },
      {
        question: '我能用Cap Rate给自己已持有的物业估值吗？',
        answer: '可以。把你物业当前的NOI，以及一个估计的市场价值（可以找经纪人要同类成交案例作参考）代入公式，就能大致判断你的Cap Rate相对市场处在什么水平。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '净营业收入 (NOI) 计算器', slug: 'noi' },
      { title: '现金回报率 (Cash-on-Cash) 计算器', slug: 'cash-on-cash' },
      { title: '1031 Exchange 递延税计算器', slug: '1031-exchange' },
      { title: '收支平衡比率 (Break-Even Ratio) 计算器', slug: 'break-even-ratio' },
    ],
  },
  noi: {
    metaTitle: 'NOI 计算器 — 商业地产净营业收入在线计算工具',
    metaDescription: '输入总收入、空置损失和运营支出，计算商业地产的净营业收入（NOI），这是几乎所有商业地产其他指标的计算基础。',
    h1: '净营业收入 (NOI) 计算器',
    subtitle: '算出你物业的净营业收入——几乎所有其他商业地产指标都是从这个数字出发的。',
    whatIsTitle: 'NOI 是什么，为什么重要',
    whatIsContent: 'NOI是商业地产投资里最基础的指标。几乎所有其他计算——Cap Rate、Cash-on-Cash Return、贷款月供——都是从NOI开始算的。它反映的是一个物业单纯从运营中产生的收入，还没算进你的房贷或所得税。贷款机构、评估师、买家都会先看NOI，因为它把物业本身的表现，和某个具体业主选择的融资方式区分开来了。',
    formulaTitle: '计算公式',
    formulaCode: 'NOI = 有效毛收入(EGI) − 运营支出\nEGI = 总收入 − 空置及坏账损失',
    formulaVariables: [
      { label: '有效毛收入 (EGI)', desc: '潜在年租金总收入减去预期的空置及坏账损失' },
      { label: '运营支出', desc: '包括物业税、保险、维修保养、物业管理费、房东承担的水电费等。不包括房贷还款、资本性改造或所得税。' },
    ],
    exampleTitle: '一个真实场景示例',
    exampleContent: '一栋12户的公寓楼，年租金总收入31.2万美元。你估计空置损失约5%（1.56万美元），运营支出（税、保险、维护、管理费）一年是9.4万美元。\n\nEGI = $312,000 − $15,600 = $296,400\nNOI = $296,400 − $94,000 = $202,400/年（约合每月$16,867）',
    faqTitle: '常见问题',
    faqs: [
      {
        question: 'NOI 包括房贷还款吗？',
        answer: '不包括。NOI是在还贷之前计算的。房贷还款是在算现金流的时候才扣除，不是在算NOI的时候扣除。',
      },
      {
        question: '哪些算运营支出？',
        answer: '物业税、保险、维修保养、物业管理费、房东承担的水电费，以及更新储备金。资本性改造（比如换屋顶）和房贷还款不算在内。',
      },
      {
        question: '为什么贷款机构这么看重NOI？',
        answer: '贷款机构会用NOI来算偿债覆盖率 (DSCR)——也就是判断这个物业产生的收入，能不能舒服地覆盖贷款还款。NOI偏低或者在下滑，在贷款审核里是一个警示信号。',
      },
      {
        question: 'NOI 和现金流有什么区别？',
        answer: 'NOI是还贷之前的数字，现金流是还贷之后的数字。现金流 = NOI − 年度还贷总额（有时还要再减掉资本储备金）。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
      { title: '偿债覆盖率 (DSCR) 计算器', slug: 'dscr' },
      { title: '收支平衡比率 (Break-Even Ratio) 计算器', slug: 'break-even-ratio' },
      { title: '1031 Exchange 递延税计算器', slug: '1031-exchange' },
    ],
  },
  cashOnCash: {
    metaTitle: 'Cash-on-Cash Return 计算器 — 商业地产现金回报率工具',
    metaDescription: '输入年现金流和实际投入现金，计算你在商业地产投资中的Cash-on-Cash Return，也就是加了杠杆之后的真实资金回报率。',
    h1: '现金回报率 (Cash-on-Cash) 计算器',
    subtitle: '算出你实际投入的现金——在加了贷款杠杆之后——真正的回报率。',
    whatIsTitle: 'Cash-on-Cash Return 是什么，为什么重要',
    whatIsContent: 'Cash-on-Cash Return衡量的是：你每年实际拿到手的税前现金流，相对于你实际投入这笔交易的现金——首付、过户成本，以及任何前期的资本性改造支出——的比率。和Cap Rate不同，它把杠杆（贷款）因素算了进去，所以它反映的是你投入的每一块钱资金实际"干活"的效率，而不是物业本身抽象意义上的表现。',
    formulaTitle: '计算公式',
    formulaCode: 'Cash-on-Cash Return = 年税前现金流 / 实际投入现金总额 × 100%',
    formulaVariables: [
      { label: '年现金流', desc: 'NOI减去年度还贷总额（贷款本息）' },
      { label: '实际投入现金总额', desc: '首付 + 过户成本 + 前期即时的资本性支出——不是物业的全部购买价' },
    ],
    exampleTitle: '一个真实场景示例',
    exampleContent: '你以120万美元买下一处物业，首付25%（30万美元），加上3万美元的过户成本和即时维修，实际投入现金总额是33万美元。年NOI是8.4万美元，年度还贷（本息）是5.4万美元。\n\n年现金流 = $84,000 − $54,000 = $30,000\nCash-on-Cash Return = $30,000 / $330,000 = 9.1%\n\n对比这个物业的Cap Rate（$84,000 / $1,200,000 = 7.0%）——这里的杠杆把你的现金回报率抬高到了Cap Rate之上，因为贷款成本低于物业本身的收益率。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '为什么Cash-on-Cash Return通常和Cap Rate不一样？',
        answer: 'Cap Rate假设没有贷款；Cash-on-Cash Return则反映了杠杆效应。如果你的贷款利率低于物业的Cap Rate，杠杆通常会把你的Cash-on-Cash Return抬高到Cap Rate之上（正向杠杆）。如果利率更高，则效果相反（负向杠杆）。',
      },
      {
        question: '什么算"投入现金"？',
        answer: '首付、过户成本、贷款手续费，以及物业出租前需要的即时维修或升级支出。不包括购买价里通过贷款融资的部分。',
      },
      {
        question: 'Cash-on-Cash Return 是不是越高越好？',
        answer: '不一定——非常高的Cash-on-Cash Return也可能意味着高杠杆、高风险（相对较小的首付、较大的贷款）。建议结合月供还款额一起看，了解你的风险缓冲空间有多大。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
      { title: '收支平衡比率 (Break-Even Ratio) 计算器', slug: 'break-even-ratio' },
      { title: '1031 Exchange 递延税计算器', slug: '1031-exchange' },
      { title: '偿债覆盖率 (DSCR) 计算器', slug: 'dscr' },
    ],
  },
  loanPayment: {
    metaTitle: '商业地产贷款月供计算器 — 等额本息与等额本金还款与气球尾款计算',
    metaDescription: '对比商业地产贷款等额本息与等额本金两种还款方式，计算每月本息还款额、利息成本支出、到期气球尾款（Balloon Payment）金额及前12个月还款摊销表。',
    h1: '商业地产贷款月供 (Loan Payment) 计算器',
    subtitle: '支持等额本息与等额本金两种还款模式切换，精准计算每月供款、利息开支及到期气球尾款。',
    whatIsTitle: '商业地产贷款还款方式与气球尾款解析',
    whatIsContent: '商业地产贷款通常采用较短的到期年限（Maturity Term，如5年、7年或10年），搭配较长的摊销年限（Amortization Term，如25年或30年）。在贷款到期日，未还清的剩余本金余额必须通过一次性“气球尾款（Balloon Payment）”偿还或重新办理再融资（Refinance）。\n\n商业贷款常见的两种还款方式：\n1. 等额本息 (Equal Installment)：每月还款总额固定不变。前期还款中利息占比较高、本金较少，因此在到期日剩余的气球尾款余额较高。\n2. 等额本金 (Equal Principal)：每月偿还固定数额的本金，利息随剩余本金减少而逐月递减，因此月供逐月下降。由于前期偿还本金速度更快，贷款到期时的气球尾款余额显著低于等额本息。',
    formulaTitle: '计算公式',
    formulaCode: '【等额本息模式】\n每月固定的本息还款额 M = P × [ r(1 + r)^n ] / [ (1 + r)^n − 1 ]\n\n【等额本金模式】\n第 m 个月的月供 M_m = (P / n) + [ P − (m − 1) × (P / n) ] × r\n每月固定偿还本金 = P / n',
    formulaVariables: [
      { label: 'P', desc: '贷款本金总额 ($)' },
      { label: 'r', desc: '月利率 (年利率 / 12)' },
      { label: 'n', desc: '总摊销期数 (摊销年限 × 12)' },
      { label: 'm', desc: '当前还款期数 (第 1 至 n 个月)' },
    ],
    exampleTitle: '真实场景对比示例 ($130万贷款, 6.5%利率, 25年摊销, 10年到期)',
    exampleContent: '',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '商业地产贷款中，等额本息与等额本金有什么主要区别？',
        answer: '主要区别在于本金还款速度与月供压力。等额本息每月还款金额固定，前期还款压力较小，但本金下降较慢，到期气球尾款较高；等额本金首月还款额最高、之后逐月下降，虽然前期现金流压力较大，但能更快偿还本金、大幅节省总利息支出，并显著降低到期时的再融资气球尾款金额。',
      },
      {
        question: '什么是气球尾款 (Balloon Payment)？',
        answer: '气球尾款是指贷款的实际到期年限（例如10年）短于其月供计算的摊销年限（例如25年），在贷款到期日需要一次性偿还的剩余未还清本金余额。商业地产投资者通常会在气球尾款到期前选择重新办理贷款（Refinance）或出售物业结清。',
      },
      {
        question: '商业地产贷款常见的摊销年限与到期年限是多少？',
        answer: '绝大多数商业地产贷款采用 25 年摊销年限（Amortization Term）来计算每月供款；而实际到期年限（Maturity Term）通常为 5 年、7 年或 10 年。优质核心城市的标杆资产可能争取到 30 年摊销。',
      },
      {
        question: '投资者应该如何选择还款方式？',
        answer: '如果项目前期现金流较紧、希望保持稳定的月度支出预算，通常选择【等额本息】；如果项目净营业收入（NOI）非常充沛、希望最大程度节省利息成本并降低未来到期再融资风险，选择【等额本金】更为有利。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: 'Lease vs Buy (租买对比) 计算器', slug: 'lease-vs-buy' },
      { title: '偿债覆盖率 (DSCR) 计算器', slug: 'dscr' },
      { title: '净营业收入 (NOI) 计算器', slug: 'noi' },
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
    ],
  },
  dscr: {
    metaTitle: 'DSCR 计算器 — 商业地产偿债覆盖率在线计算与贷款风险评估',
    metaDescription: '输入年净营业收入（NOI）与年度还贷总额（本金+利息），在线计算商业地产偿债覆盖率（DSCR），评估贷款安全边际与商业银行放贷审核标准。',
    h1: '偿债覆盖率 (DSCR) 计算器',
    subtitle: '评估你物业产生的净营业收入（NOI）能否充足覆盖年度房贷还款，了解商业地产贷款机构的审核门槛。',
    whatIsTitle: 'DSCR 是什么，为什么重要',
    whatIsContent: '偿债覆盖率 (Debt Service Coverage Ratio, DSCR) 是商业地产贷款审核中最核心的风险衡量指标。它用物业的年净营业收入 (NOI) 除以年度还贷总额（贷款本金与利息之和），直接反映物业靠自身运营产生的现金流偿还房贷的“安全边际”。\n\n商业银行和机构贷款人普遍要求 DSCR 至少达到 1.20 至 1.25x。这意味着物业不仅要能全额还清房贷，还要保留 20%-25% 的净收入作为应对空置率上升、租金下跌或运营成本增加的风险缓冲区。',
    formulaTitle: '计算公式',
    formulaCode: 'DSCR = 年净营业收入 (NOI) / 年度还贷总额 (Annual Debt Service)',
    formulaVariables: [
      { label: '年净营业收入 (NOI)', desc: '有效毛收入减去运营支出后的净收益（未扣除房贷本息与所得税）' },
      { label: '年度还贷总额 (Annual Debt Service)', desc: '一年内支付的贷款本金与利息总和（12 个月月供之和）' },
    ],
    exampleTitle: '真实场景示例 ($200万商业办公楼)',
    exampleContent: '假设你拟购入一栋小型商业办公楼，购买价 200 万美元，申请贷款 150 万美元。该物业年有效毛收入 22 万美元，运营支出 7 万美元，因此年净营业收入 (NOI) 为 $150,000。\n\n按照 6.5% 利率、25 年摊销计算，每月供款为 $10,128，年度还贷总额 (Annual Debt Service) 为 $121,536。\n\nDSCR = $150,000 / $121,536 = 1.23x\n\n【结果解读】：1.23x 处在多数商业银行最低门槛 (1.20 - 1.25x) 附近。贷款机构可能会要求增加首付以降低贷款金额，或要求设立额外的还贷储备金。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '商业地产贷款常见的 DSCR 门槛是多少？',
        answer: '绝大多数商业银行、CMBS 及机构贷款人要求的最低 DSCR 门槛在 1.20x 至 1.25x 之间。优质核心资产或稳定租客的单租户 NNN 物业门槛可能放宽至 1.15x，而高风险资产（如酒店或老旧未改造物业）要求通常升至 1.35x - 1.50x。',
      },
      {
        question: '如果 DSCR 低于 1.0 会发生什么？',
        answer: 'DSCR 低于 1.0x 意味着物业产生的净收益不足以支付房贷（即现金流倒挂）。在申请新贷款时，银行会直接拒绝审批；在现有贷款存续期内，可能会触发贷款违约条款（Technical Default），银行有权要求借款人注入额外资本或增加抵押物。',
      },
      {
        question: '如何提高物业的 DSCR 以符合贷款条件？',
        answer: '主要有两种方式：一是提高 NOI（通过提升租金、降低空置率或削减运营支出）；二是降低年度还贷总额（增加首付比例以减少贷款本金、争取更低利率，或延长摊销年限）。',
      },
      {
        question: 'DSCR 和 NOI、Cap Rate 有什么关系？',
        answer: 'NOI 是计算 DSCR 的分子。Cap Rate 决定了物业的总价值与购买价，而 DSCR 则决定了在给定的 NOI 下，你最多能从银行贷出多少资金（即最大可支持贷款额）。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '净营业收入 (NOI) 计算器', slug: 'noi' },
      { title: '贷款月供 (Loan Payment) 计算器', slug: 'loan-payment' },
      { title: '1031 Exchange 递延税计算器', slug: '1031-exchange' },
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
    ],
  },
  exchange1031: {
    metaTitle: '1031 Exchange 递延税计算器 — 商业地产资本利得税延税估算工具',
    metaDescription: '输入拟出售售价、原始成本基准、交易费用及预计综合税率，在线估算商业地产 1031 Like-Kind Exchange 置换可延迟缴纳的资本利得税及再投资目标。',
    h1: '1031 Exchange 递延税计算器',
    subtitle: '估算出售商业地产时通过 1031 同类置换（Like-Kind Exchange）可延迟缴纳的资本利得税与再投资门槛。',
    whatIsTitle: '1031 Exchange 是什么，为什么重要',
    whatIsContent: '根据美国国内税收法典第 1031 条款（IRC Section 1031），商业地产或投资性地产业主在出售物业时，只要将变现资金按规定重新投资于“同类资产（Like-Kind Property）”，即可暂缓缴纳全部或大部分资本利得税及折旧追回税。\n\n1031 Exchange 是商业地产投资者积累财富的核心税务工具，能将原本需要缴给税务局的资金留在投资组合中继续产生杠杆与收益。要实现 100% 全额延税，需满足两大规则：\n1. 新购买的目标物业总买价必须大于或等于原物业的卖出净额（Sale Price minus Selling Expenses）。\n2. 原物业出售结清后的全部净现金（Equity）必须全额投入到新物业中。',
    formulaTitle: '计算公式',
    formulaCode: '变现资本利得 (Realized Gain) = 售价 − 出售费用 − 原始成本基准\n预计递延税负 (Estimated Deferred Tax) = 变现资本利得 × 综合税率',
    formulaVariables: [
      { label: '售价 (Sale Price)', desc: '拟出售物业的合同总销售价格' },
      { label: '出售费用 (Selling Expenses)', desc: '交易经纪佣金、产权过户费、律师费及托管费' },
      { label: '原始成本基准 (Original Cost Basis)', desc: '原始购入价格加上资本性升级改进成本（注：未扣除历史累计折旧）' },
      { label: '综合税率 (Combined Tax Rate)', desc: '包含联邦资本利得税 (15%-20%)、州税 (0%-13.3%)、折旧追回税 (25%) 及 NIIT (3.8%) 的预估综合税率' },
    ],
    exampleTitle: '一个真实 1031 置换场景示例 ($250万卖出)',
    exampleContent: '假设你在 8 年前以 $1,200,000 购入一处商业物业，现以 $2,500,000 出售，支付出售过户费用 $150,000。预计综合资本利得及折旧追回税率为 25%。\n\n卖出净所得 (Net Proceeds) = $2,500,000 − $150,000 = $2,350,000\n变现资本利得 (Realized Gain) = $2,350,000 − $1,200,000 = $1,150,000\n若直接出售（不走 1031）：应缴税款金额款项 = $1,150,000 × 25% = $287,500\n\n【1031 置换结果】：通过合格中介人 (QI) 办理 1031 Exchange，可延迟缴纳全部 $287,500 税款。你只需在 45 天内指定、180 天内完成购入总价不低于 $2,350,000 的新商业物业，即可将这 $28.75 万本应交税的资金继续留在你的商业地产组合中增长。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '1031 Exchange 的 45 天与 180 天时间节点是如何计算的？',
        answer: '两个时间窗口均从原物业过户交割日（Closing Date）当天开始起算：1. 必须在 45 天内向合格中介人 (QI) 书面指定拟购买的目标备选物业（最多可指定 3 处）；2. 必须在 180 天内（或递交当年所得税申报表截止日前，以较早者为准）完成目标物业的产权交割。这两个时间节点极其严格，没有任何宽限期。',
      },
      {
        question: '什么是合格中介人 (Qualified Intermediary, QI)？',
        answer: '根据 IRS 规定，卖家在交易过程中绝对不能亲手触碰出售原物业所得的任何现金。必须聘请独立合规的 QI 设立托管账户接收出售资金，并在购入新物业时由 QI 直接将资金划拨至过户公司。若卖家提前或自行触碰资金，1031 Exchange 将立即失效。',
      },
      {
        question: '如果新买的物业价格低于原出售净额会怎样（Boot）？',
        answer: '如果新物业买价低于原出售净额，或未将出售净现金全部投入新项目，差额部分将被 IRS 认定为“Boot”（非同类所得），该 Boot 部分需要按规定缴纳资本利得税。',
      },
      {
        question: '1031 Exchange 可以用于个人自住所吗？',
        answer: '不可以。1031 Exchange 严格限定于“用于商业运营或投资目的的不动产（Held for Productive Use in a Trade or Business or for Investment）”。个人自住主用住宅不适用 1031 条款（自住房免税适用 IRC Section 121 条款）。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
      { title: '净营业收入 (NOI) 计算器', slug: 'noi' },
      { title: '现金回报率 (Cash-on-Cash) 计算器', slug: 'cash-on-cash' },
    ],
  },
  leaseVsBuy: {
    metaTitle: 'Lease vs Buy 对比工具 — 商业地产租买决策与全周期成本分析',
    metaDescription: '输入租赁租金、递增率与购买价格、首付、贷款利率、升值预估，对比商业企业或投资者 5-15 年持有周期内的租赁与自购总成本及净资产积累。',
    h1: 'Lease vs Buy (租买对比) 计算器',
    subtitle: '对比商业地产租赁方案与购买自用方案的全周期财务成本、现金流支出与资产增值收益。',
    whatIsTitle: 'Lease vs Buy 是什么，为什么重要',
    whatIsContent: 'Lease vs Buy（租赁与购买对比）分析是商业企业（Owner-Occupier）与商业地产投资者在确定办公楼、零售门面或仓储物流空间时的核心财务决策工具。\n\n租赁方案前期资金占用少、灵活度高，但付出的所有租金均为纯开支，期末无法积累任何资产权益；购买方案虽然需要支付前期首付（Down Payment）与按揭还款，但每月还贷中的本金部分（Principal Paydown）转化为硬性资产储备，且能享受物业长期增值的红利。本计算器将两者的全周期现金流支出与退出变现净收益放在同一标准下进行并排对比。',
    formulaTitle: '计算公式',
    formulaCode: '租赁方案总支出 = 逐年累加 [ 年租金 × (1 + 租金年涨幅)^年数 ]\n购买方案净成本 = 首付 + 累计还贷总额 − 退出时卖出净变现所得\n退出时卖出净变现 = 购买价格 × (1 + 预估增值率)^年数 × (1 − 卖出成本%) − 剩余贷款余额',
    formulaVariables: [
      { label: '月租金与递增率', desc: '首年基础月租金及合同约定的年租金递增比例 (通常为 2.5% - 3.5%)' },
      { label: '购买价格与首付', desc: '物业买价及首付款比例 (商业自用贷款如 SBA 504/7(a) 首付低至 10%-20%，常规商业贷款为 25%)' },
      { label: '退出增值与卖出成本', desc: '持有期末预估的年均资产增值率及卖出时支付的经纪佣金与过户费 (通常为 5%-6%)' },
    ],
    exampleTitle: '一个真实 10 年期租买对比场景示例 ($180万买价 vs $1万月租)',
    exampleContent: '假设一家商业企业计划使用一处办公空间 10 年：\n- 方案 A (租赁)：首年月租金 $10,000，年递增率 3.0%。10 年累计支付租金总额为 $1,375,666。\n- 方案 B (购买)：买价 $1,800,000，首付 25% ($450,000)，贷款 $1,350,000 (利率 6.5%, 25 年摊销)。年均增值 3.0%，第 10 年卖出佣金成本 5%。\n  - 10 年累计支付贷款本息总额：$1,093,836\n  - 第 10 年物业估值升至 $2,419,049，扣除卖出成本及剩余贷款余额 ($1,046,403) 后，净变现拿回现金：$1,251,694\n  - 购买方案 10 年实际净成本 = $450,000 + $1,093,836 − $1,251,694 = $292,142\n\n【对比结论】：在该场景下，10 年持有期内购买方案相比租赁方案可节省现金成本约 $1,083,524。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '企业在什么情况下应该选择租赁而非购买？',
        answer: '如果企业处于初创或爆发式扩张期、现金流需要优先投向主营业务扩张，或者业务地点具有不确定性（未来 3-5 年可能需要扩租或搬迁），选择【租赁】更为明智，可避免沉淀大量资本于房地产中。',
      },
      {
        question: '自用企业购买商业地产有什么特殊的贷款优惠？',
        answer: '在美自用企业（占用面积超过 51%）可以申请美国小企业管理局 (SBA) 提供的 SBA 504 或 SBA 7(a) 贷款。这类贷款首付比例低至 10%，且提供长达 25 年的固定利率长周期融资，大幅降低了购买门槛。',
      },
      {
        question: '购买方案中的“净成本”是如何算出来的？',
        answer: '购买方案的净成本考虑了变现所得：净成本 =（首付款 + 持有期内付出的全部房贷本息）减去（持有期末卖掉物业拿回的净现金）。因为卖掉物业时拿回的现金远远超过了付出的本金，所以长期来看购买的净成本通常显著低于租赁。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '贷款月供 (Loan Payment) 计算器', slug: 'loan-payment' },
      { title: '偿债覆盖率 (DSCR) 计算器', slug: 'dscr' },
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
    ],
  },
  breakEvenRatio: {
    metaTitle: '收支平衡比率 (Break-Even Ratio) 计算器 — 商业地产空置与抗风险能力评估',
    metaDescription: '输入年度运营支出、年度还贷总额与有效毛收入（EGI），在线计算商业地产收支平衡比率 (Break-Even Ratio)，评估保本出租率与商业银行风控放贷标准。',
    h1: '收支平衡比率 (Break-Even Ratio) 计算器',
    subtitle: '计算商业地产物业满足运营支出与还贷债务所需的最低出租率门槛与抗空置安全垫。',
    whatIsTitle: 'Break-Even Ratio 是什么，为什么重要',
    whatIsContent: '收支平衡比率（Break-Even Ratio，简称 BER）是商业地产贷款机构（Lenders）与投资者评估物业“抗空置能力”与“防止现金流倒挂（Negative Cash Flow）”的关键风控指标。\n\n该指标表明：物业的实际出租率必须达到多少，产生的毛收入才刚好够支付全部运营支出（Operating Expenses）和贷款本息（Debt Service）。BER 越低，说明物业的抗风险能力越强，能够承受越高的空置率或租金下滑风险；反之，BER 越高，说明财务安全垫越薄，极易陷入亏损。商业银行通常要求 BER 控制在 80% 至 85% 以下。',
    formulaTitle: '计算公式',
    formulaCode: '收支平衡比率 (%) = ( 年度运营支出 + 年度还贷总额 ) / 年有效毛收入 (EGI) × 100%\n最高可承受空置率 (%) = 100% − 收支平衡比率',
    formulaVariables: [
      { label: '年度运营支出 (Operating Expenses)', desc: '物业维持日常运营所需的全部固定与变动开支（房产税、保险、管理费、维修等）' },
      { label: '年度还贷总额 (Annual Debt Service)', desc: '物业按揭贷款全年的本金与利息还款总额 (12 × 月供)' },
      { label: '年有效毛收入 (Effective Gross Income)', desc: '潜在租金总收入扣除预期空置与欠租损失后的实际毛收入 (EGI)' },
    ],
    exampleTitle: '一个真实商业办公楼收支平衡比率示例 ($22万 EGI)',
    exampleContent: '假设你持有一栋年有效毛收入 (EGI) 为 $220,000 的商业办公楼，年度运营支出为 $70,000，按揭贷款年度还贷总额 (Annual Debt Service) 为 $121,536：\n\n刚性固定支出总额 = $70,000 + $121,536 = $191,536\n收支平衡比率 (BER) = ($191,536 / $220,000) × 100% = 87.06%\n最高可承受空置率 = 100% − 87.06% = 12.94%\n\n【结果解读】：由于 BER 达到了 87.06%（超过了商业银行普遍设定的 80%-85% 警戒线），说明该物业抗空置能力偏弱。一旦空置率超过 12.94%，物业产生的收入将无法覆盖账面开支，业主需自筹资金补贴打款。建议通过增加首付降贷或提升租金来降低 BER。',
    faqTitle: '常见问题',
    faqs: [
      {
        question: '商业银行普遍接受的最高 Break-Even Ratio 是多少？',
        answer: '多数商业地产放贷机构要求 Break-Even Ratio 不得超过 80% 至 85%。BER 低于 80% 被视为具有良好的财务安全缓冲，更容易获得贷款审批与优惠利率。',
      },
      {
        question: 'Break-Even Ratio 和 DSCR 有什么区别与联系？',
        answer: '两个指标均衡量偿债能力，但视角不同：DSCR = NOI / Debt Service，关注净收入覆盖还贷的倍数；而 Break-Even Ratio = (Operating Expenses + Debt Service) / EGI，将运营开支与还贷加总后除以毛收入，直观反映了“保本所需的最少出租率”。两者相辅相成。',
      },
      {
        question: '如何有效降低物业的收支平衡比率？',
        answer: '主要途径有三：1. 降低贷款债务（增加首付比例、争取更低利率或延长摊销年限）；2. 优化运营成本（重新竞标物业保险、申请房产税减免）；3. 提升毛收入（增设停车场/广告牌等额外收入来源）。',
      },
    ],
    relatedTitle: '相关计算器',
    relatedCalculators: [
      { title: '偿债覆盖率 (DSCR) 计算器', slug: 'dscr' },
      { title: '净营业收入 (NOI) 计算器', slug: 'noi' },
      { title: '资本化率 (Cap Rate) 计算器', slug: 'cap-rate' },
    ],
  },
};
